import { Aktualita } from "../models/Aktualita";

export const AKTUALITY: Aktualita[] = [
    {date:"12.12.2024", title: "Lukášove prvotné obavy opadli", slug:"lukasove-prvotne-obavy-opadli", titleImage:"assets/img/adamec.jpg", text: "Jeden z oslovených košických známych osobností bol spevák a hudobník Lukáš Adamec. Nebol proti, ale oblečenia sa do kroja sa obával. Kroj na sebe nikdy nemal a ani obleky nie sú jeho obľúbený outfit. Nakoniec však výber kroja v našej krojárni netrval až tak dlho, ako sme si mysleli. Kroj z Bystrian, ktorý ma na sebe, mu naozaj sadol. Vyzeral v ňom úplne prirodzene, ako by sa v ňom narodil 🙂 Hlavnou motiváciou však bolo pomôcť. Venoval svoj čas, aby pomohol ušľachtilému zámeru. Ďakujeme Lukášovi aj fotografom z Open Photo Point.", images: [""]},
    {date:"13.12.2024", title: "V kroji je zašitá duša", slug:"v-kroji-je-zasita-dusa", titleImage: "assets/img/kosicka.jpg", text: "Táto sekcia je určená pre textový obsah danej aktuality. Momentálne tu ešte nie je pridaný žiadny obsah, preto text slúži len ako dočasná výplň. Ďakujeme za trpezlivosť. Medzitým môžete navštíviť aj ďalšie sekcie našej stránky, kde nájdete množstvo zaujímavého obsahu.O všetkých novinkách vás budeme pravidelne informovať.", images: [""]},
    {date:"14.12.2024", title: "Pre ŽELEZIAR to urobím.", slug:"pre-zeleziar-to-urobim", titleImage: "assets/img/kolcun.jpg", text: "Táto sekcia je určená pre textový obsah danej aktuality. Momentálne tu ešte nie je pridaný žiadny obsah, preto text slúži len ako dočasná výplň. Ďakujeme za trpezlivosť. Medzitým môžete navštíviť aj ďalšie sekcie našej stránky, kde nájdete množstvo zaujímavého obsahu.O všetkých novinkách vás budeme pravidelne informovať.", images: [""]},
    {date:"15.12.2024", title: "Lukášove prvotné obavy neopadli", slug:"lukasove-prvotne-obavy-neopadli", titleImage:"assets/img/adamec.jpg", text: "Jeden z oslovených košických známych osobností bol spevák a hudobník Lukáš Adamec. Nebol proti, ale oblečenia sa do kroja sa obával. Kroj na sebe nikdy nemal a ani obleky nie sú jeho obľúbený outfit. Nakoniec však výber kroja v našej krojárni netrval až tak dlho, ako sme si mysleli. Kroj z Bystrian, ktorý ma na sebe, mu naozaj sadol. Vyzeral v ňom úplne prirodzene, ako by sa v ňom narodil 🙂 Hlavnou motiváciou však bolo pomôcť. Venoval svoj čas, aby pomohol ušľachtilému zámeru. Ďakujeme Lukášovi aj fotografom z Open Photo Point.", images: [""]},
    {date:"16.12.2024", title: "Pre ŽELEZIAR to neurobím.", slug:"pre-zeleziar-to-neurobim", titleImage: "assets/img/kolcun.jpg", text: "Táto sekcia je určená pre textový obsah danej aktuality. Momentálne tu ešte nie je pridaný žiadny obsah, preto text slúži len ako dočasná výplň. Ďakujeme za trpezlivosť. Medzitým môžete navštíviť aj ďalšie sekcie našej stránky, kde nájdete množstvo zaujímavého obsahu.O všetkých novinkách vás budeme pravidelne informovať.", images: [""]},
    {date:"17.12.2024", title: "V kroji nie je zašitá duša", slug:"v-kroji-nie-je-zasita-dusa", titleImage: "assets/img/kosicka.jpg", text: "Táto sekcia je určená pre textový obsah danej aktuality. Momentálne tu ešte nie je pridaný žiadny obsah, preto text slúži len ako dočasná výplň. Ďakujeme za trpezlivosť. Medzitým môžete navštíviť aj ďalšie sekcie našej stránky, kde nájdete množstvo zaujímavého obsahu.O všetkých novinkách vás budeme pravidelne informovať.", images: [""]},
]