import { Aktualita } from "../models/Aktualita";

export const AKTUALITY: Aktualita[] = [
    {date:"12.12.2024", title: "Lukášove prvotné obavy opadli", slug:"lukasove-prvotne-obavy-opadli", titleImage:"assets/img/adamec.jpg", text: "Jeden z oslovených košických známych osobností bol spevák a hudobník Lukáš Adamec. Nebol proti, ale oblečenia sa do kroja sa obával. Kroj na sebe nikdy nemal a ani obleky nie sú jeho obľúbený outfit. Nakoniec však výber kroja v našej krojárni netrval až tak dlho, ako sme si mysleli. Kroj z Bystrian, ktorý ma na sebe, mu naozaj sadol. Vyzeral v ňom úplne prirodzene, ako by sa v ňom narodil 🙂 Hlavnou motiváciou však bolo pomôcť. Venoval svoj čas, aby pomohol ušľachtilému zámeru. Ďakujeme Lukášovi aj fotografom z Open Photo Point.", images: [""]},
    {date:"13.12.2024", title: "V kroji je zašitá duša", slug:"v-kroji-je-zasita-dusa", titleImage: "assets/img/kosicka.jpg", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", images: [""]},
    {date:"14.12.2024", title: "Pre ŽELEZIAR to urobím.", slug:"pre-zeleziar-to-urobim", titleImage: "assets/img/kolcun.jpg", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", images: [""]},
    {date:"15.12.2024", title: "Lukášove prvotné obavy neopadli", slug:"lukasove-prvotne-obavy-neopadli", titleImage:"assets/img/adamec.jpg", text: "Jeden z oslovených košických známych osobností bol spevák a hudobník Lukáš Adamec. Nebol proti, ale oblečenia sa do kroja sa obával. Kroj na sebe nikdy nemal a ani obleky nie sú jeho obľúbený outfit. Nakoniec však výber kroja v našej krojárni netrval až tak dlho, ako sme si mysleli. Kroj z Bystrian, ktorý ma na sebe, mu naozaj sadol. Vyzeral v ňom úplne prirodzene, ako by sa v ňom narodil 🙂 Hlavnou motiváciou však bolo pomôcť. Venoval svoj čas, aby pomohol ušľachtilému zámeru. Ďakujeme Lukášovi aj fotografom z Open Photo Point.", images: [""]},
    {date:"16.12.2024", title: "Pre ŽELEZIAR to neurobím.", slug:"pre-zeleziar-to-neurobim", titleImage: "assets/img/kolcun.jpg", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", images: [""]},
    {date:"17.12.2024", title: "V kroji nie je zašitá duša", slug:"v-kroji-nie-je-zasita-dusa", titleImage: "assets/img/kosicka.jpg", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", images: [""]},
]