import { Aktualita } from "../models/Aktualita";

export const AKTUALITY: Aktualita[] = [
    {title: "Lukášove prvotné obavy opadli", titleImage:"assets/img/adamec.jpg", text: "Jeden z oslovených košických známych osobností bol spevák a hudobník Lukáš Adamec. Nebol proti, ale oblečenia sa do kroja sa obával. Kroj na sebe nikdy nemal a ani obleky nie sú jeho obľúbený outfit. Nakoniec však výber kroja v našej krojárni netrval až tak dlho, ako sme si mysleli. Kroj z Bystrian, ktorý ma na sebe, mu naozaj sadol. Vyzeral v ňom úplne prirodzene, ako by sa v ňom narodil 🙂 Hlavnou motiváciou však bolo pomôcť. Venoval svoj čas, aby pomohol ušľachtilému zámeru. Ďakujeme Lukášovi aj fotografom z Open Photo Point.", images: [""]},
    {title: "V kroji je zašitá duša", titleImage: "assets/img/kosicka.jpg", text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", images: [""]},
    {title: "Pre ŽELEZIAR to urobím.", titleImage: "assets/img/kolcun.jpg", text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", images: [""]},
    {title: "Lukášove prvotné obavy opadli", titleImage:"assets/img/adamec.jpg", text: "Jeden z oslovených košických známych osobností bol spevák a hudobník Lukáš Adamec. Nebol proti, ale oblečenia sa do kroja sa obával. Kroj na sebe nikdy nemal a ani obleky nie sú jeho obľúbený outfit. Nakoniec však výber kroja v našej krojárni netrval až tak dlho, ako sme si mysleli. Kroj z Bystrian, ktorý ma na sebe, mu naozaj sadol. Vyzeral v ňom úplne prirodzene, ako by sa v ňom narodil 🙂 Hlavnou motiváciou však bolo pomôcť. Venoval svoj čas, aby pomohol ušľachtilému zámeru. Ďakujeme Lukášovi aj fotografom z Open Photo Point.", images: [""]},
    {title: "Pre ŽELEZIAR to urobím.", titleImage: "assets/img/kolcun.jpg", text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", images: [""]},
    {title: "V kroji je zašitá duša", titleImage: "assets/img/kosicka.jpg", text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", images: [""]},
]