export const KROJE: {name: string , img: string}[] = [
    {name: "Abelová, Podpoľanie", img: "assets/img/ponuka-krojov/Ábelová.jpg"},
    {name: "Myslava, Abov", img: "assets/img/ponuka-krojov/Abovský kroj myslava.jpg"},
    {name: "Neviem, Zistim", img: "assets/img/ponuka-krojov/BI4F5462.jpg"},
    {name: "Myslava, Abov", img: "assets/img/ponuka-krojov/BI4F5536.jpg"},
    {name: "Neviem, Zistim", img: "assets/img/ponuka-krojov/BI4F5572.jpg"},
    {name: "Jakubany, Spiš", img: "assets/img/ponuka-krojov/BI4F5586.jpg"},
    {name: "Dlhé Klčovo, Zemplín", img: "assets/img/ponuka-krojov/BI4F5605.jpg"},
    {name: "Neviem, Zistim", img: "assets/img/ponuka-krojov/BI4F5665.jpg"},
    {name: "Rejdová, Gemer", img: "assets/img/ponuka-krojov/BI4F5687.jpg"},
    {name: "Parchovany, Zemplín", img: "assets/img/ponuka-krojov/BI4F5703.jpg"},
    {name: "Neviem, Zistim", img: "assets/img/ponuka-krojov/BI4F5727.jpg"},
    {name: "Neviem, Zistim", img: "assets/img/ponuka-krojov/BI4F5741.jpg"},
    {name: "Žipov, Zemplín", img: "assets/img/ponuka-krojov/BI4F5773.jpg"},
    {name: "Kamienka, Spiš", img: "assets/img/ponuka-krojov/BI4F5781.jpg"},
    {name: "Myslava, Abov", img: "assets/img/ponuka-krojov/BI4F5834.jpg"},
    {name: "Krivany, Spiš", img: "assets/img/ponuka-krojov/BI4F5847.jpg"},
    {name: "Bystrany, Spiš", img: "assets/img/ponuka-krojov/BI4F5858.jpg"},
    {name: "Raslavice, Šariš", img: "assets/img/ponuka-krojov/BI4F5902.jpg"},
    {name: "Zámutov, Zemplín", img: "assets/img/ponuka-krojov/BI4F5915.jpg"},
    {name: "Myslava, Abov", img: "assets/img/ponuka-krojov/kroj Abov, okolie Košíc.jpg"},
    {name: "Neviem, Zistim", img: "assets/img/ponuka-krojov/kroj Kojšov.jpg"}
]