import { Predstavenie } from "../models/Predstavenie";

export const PREDSTAVENIA: Predstavenie[] = [
    {date:"8.12.2024", time:"18:00", duration:"60min", city: "Košice", place: "Stará radnica", name:"Humanitný koncert", info: "Tu su informacie o humanitnom koncerte", tickets:"https://zeleziar.sk/"},
    {date:"13.12.2024", time:"17:00", duration:"60min", city: "Košice", place: "Rodošto", name:"Abovské folklórne slávnosti", info: "Tu su informacie o slavnostiach", tickets:"https://zeleziar.sk/"},
    {date:"21.12.2024", time:"18:00",  duration:"30min", city: "Košice", place: "Veritas", name:"Vianoce s Borievkou", info: "Tu su informacie o Vianociach s Borievkou", tickets:"https://zeleziar.sk/"},
    {date:"12.7.2025", time:"-",  duration:"90min", city: "Kravany", place: "Kravany", name:"Taka tota nasa nouta", info: "vystúpenie súboru v obci Kravany", tickets:"https://zeleziar.sk/"},
    {date:"20.7.2025", time:"-",  duration:"90min", city: "Nižná Myšľa", place: "Nižná Myšľa", name:"Taka tota nasa nouta", info: "vystúpenie súboru v na 755. výročí obce", tickets:"https://zeleziar.sk/"},
    {date:"26.7.2025", time:"21:00",  duration:"70min", city: "Lúčenec", place: "Lúčenec", name:"Taka tota nasa nouta", info: "vystúpenie súboru spolu s FS Podpoľanec", tickets:"https://zeleziar.sk/"},
    {date:"27.7.2025", time:"18:30",  duration:"90min", city: "Liptovská teplička", place: "Folklórne slávností Pod Kráľovou hoľou", name:"Taka tota nasa nouta", info: "", tickets:"https://zeleziar.sk/"},
    {date:"8.12.2024", time:"18:00", duration:"60min", city: "Košice", place: "Stará radnica", name:"Humanitný koncert", info: "Tu su informacie o humanitnom koncerte", tickets:"https://zeleziar.sk/"},
    {date:"13.12.2024", time:"17:00", duration:"60min", city: "Košice", place: "Rodošto", name:"Abovské folklórne slávnosti", info: "Tu su informacie o slavnostiach", tickets:"https://zeleziar.sk/"},
    {date:"21.12.2024", time:"18:00",  duration:"30min", city: "Košice", place: "Veritas", name:"Vianoce s Borievkou", info: "Tu su informacie o Vianociach s Borievkou", tickets:"https://zeleziar.sk/"},
    {date:"12.7.2025", time:"-",  duration:"90min", city: "Kravany", place: "Kravany", name:"Taka tota nasa nouta", info: "vystúpenie súboru v obci Kravany", tickets:"https://zeleziar.sk/"},
    {date:"20.7.2025", time:"-",  duration:"90min", city: "Nižná Myšľa", place: "Nižná Myšľa", name:"Taka tota nasa nouta", info: "vystúpenie súboru v na 755. výročí obce", tickets:"https://zeleziar.sk/"},
    {date:"26.7.2025", time:"21:00",  duration:"70min", city: "Lúčenec", place: "Lúčenec", name:"Taka tota nasa nouta", info: "vystúpenie súboru spolu s FS Podpoľanec", tickets:"https://zeleziar.sk/"},
    {date:"27.7.2025", time:"18:30",  duration:"90min", city: "Liptovská teplička", place: "Folklórne slávností Pod Kráľovou hoľou", name:"Taka tota nasa nouta", info: "", tickets:"https://zeleziar.sk/"},
    {date:"27.7.2025", time:"18:30",  duration:"90min", city: "Liptovská teplička", place: "Folklórne slávností Pod Kráľovou hoľou", name:"Taka tota nasa nouta", info: "", tickets:"https://zeleziar.sk/"},
    {date:"8.12.2024", time:"18:00", duration:"60min", city: "Košice", place: "Stará radnica", name:"Humanitný koncert", info: "Tu su informacie o humanitnom koncerte", tickets:"https://zeleziar.sk/"},
    {date:"13.12.2024", time:"17:00", duration:"60min", city: "Košice", place: "Rodošto", name:"Abovské folklórne slávnosti", info: "Tu su informacie o slavnostiach", tickets:"https://zeleziar.sk/"},
    {date:"21.12.2024", time:"18:00",  duration:"30min", city: "Košice", place: "Veritas", name:"Vianoce s Borievkou", info: "Tu su informacie o Vianociach s Borievkou", tickets:"https://zeleziar.sk/"},
    {date:"12.7.2025", time:"-",  duration:"90min", city: "Kravany", place: "Kravany", name:"Taka tota nasa nouta", info: "vystúpenie súboru v obci Kravany", tickets:"https://zeleziar.sk/"},
    {date:"20.7.2025", time:"-",  duration:"90min", city: "Nižná Myšľa", place: "Nižná Myšľa", name:"Taka tota nasa nouta", info: "vystúpenie súboru v na 755. výročí obce", tickets:"https://zeleziar.sk/"},
    {date:"26.7.2025", time:"21:00",  duration:"70min", city: "Lúčenec", place: "Lúčenec", name:"Taka tota nasa nouta", info: "vystúpenie súboru spolu s FS Podpoľanec", tickets:"https://zeleziar.sk/"},
    {date:"27.7.2025", time:"18:30",  duration:"90min", city: "Liptovská teplička", place: "Folklórne slávností Pod Kráľovou hoľou", name:"Taka tota nasa nouta", info: "", tickets:"https://zeleziar.sk/"},
]