import { Premiera } from "../models/Premiera";

export const PREMIERY: Premiera[] = [
    {date:"10.12.1994", city: "Košice", place: "Štátne divadlo", name:"Vichodňarom na dzeku, druhim pre pocechu", info: "Šarišské, zemplínske, spišské a abovské piesne a tance."},
    {date:"12.11.1995", city: "Košice", place: "Štátne divadlo", name:"Ked nas sece tu nas mace", info: "Prvý celovečerný program z Abova"},
    {date:"25.10.1996", city: "Košice", place: "Jumbo centrum", name:"Vichodňarska šou, alebo hutoraci hlavi hore", info: "Spoločný zábavný program s humoristickou skupinou Drišľak"},
    {date:"27.12.1996", city: "Košice", place: "Štátne divadlo", name:"Zdravie, šťastie, pokoj svätý vinšujeme Vám", info: "Vianočný koncert"},
    {date:"22.11.1997", city: "Košice", place: "Športová hala, Moyzesova", name:"Javiskový tanečný maratón", info: "Pokus o zápis do Guinessovej knihy rekordov"},
    {date:"23.4.1999", city: "Košice", place: "Divadlo Thália", name:"U gazdovim dvore alebo špivane divadlo", info: "Hudobno-spevácky program"},
    {date:"1.5.1999", city: "Košice", place: "Štátne divadlo", name:"Kráľovstvo tanca", info: "Celosúborový program komponovaný na motívy zemplínskych rozprávok"},
    {date:"Máj 1999", city: "Košice", place: "Štátne divadlo", name:"História súboru", info: "Koncert bývalých členov súboru"},
    {date:"30.1.2000", city: "Košice", place: "Jumbo centrum", name:"Vichodňarska šou 2000", info: "Spoločný zábavný program s humoristickou skupinou Drišľak"},
    {date:"27.5.2001", city: "Košice", place: "Štátne divadlo", name:"Vydumané tance a scénické výstrelky", info: "Zvláštnosti z tvorby folklórneho súboru Železiar"},
    {date:"16.3.2002", city: "Košice", place: "Štátne divadlo", name:"Hriech?", info: "Tanečné divadlo"},
    {date:"29.6.2003", city: "Košice", place: "Štátne divadlo", name:"Gadži, Romale - Čhavale", info: "Folklór Zemplínčanov, Maďarov a olaských i usadených Rómov zo Slovenska, Maďarska a Rumunska v interpretácii folklórneho súboru Železiar."},
    {date:"22.5.2004", city: "Košice", place: "Štátne divadlo", name:"Výročnica", info: "Slávnostný program súboru Železiar a hostí pri príležitosti 40. výročia"},
    {date:"4.6.2005", city: "Košice", place: "Štátne divadlo", name:"Vichodňarom na dzeku, druhim pre pocechu II.", info: "Nanovonaštudovaný program"},
    {date:"4.6.2006", city: "Košice", place: "Štátne divadlo", name:"Rusnácka maňira", info: "Tanečný hudobný a vokálny folklór Rusínov a Ukrajincov Spiša, Šariša a Zemplína v interpretácii folklórneho súboru Železiar"},
    {date:"3.6.2007", city: "Košice", place: "Štátne divadlo", name:"Spišiaci", info: "Folklór zo Spišského regiónu (Margecany, Bystrany, Olcnava, Jakubany, Poráč, Smižany, Torysky)"},
    {date:"10.1.2008", city: "Košice", place: "Jumbo centrum", name:"Železiar a Diabli tanca", info: "Úspešná tanečná show súboru Železiar a najlepších tanečníkov ROMAFESTU z Tirgu Mureš v Rumunsku."},
    {date:"27.4.2008", city: "Košice", place: "Štátne divadlo", name:"Muž a žena v tanci", info: ""},
    {date:"15.5.2009", city: "Košice", place: "Historická radnica", name:"Všetky sú pekné do jednej", info: "Hudobno-spevácka premiéra pripravená ku 45. výročiu založenia súboru"},
    {date:"16.5.2009", city: "Košice", place: "Štátne divadlo", name:"Čo bolo, bolo…", info: ""},
    {date:"18.4.2010", city: "Košice", place: "Štátne divadlo", name:"Kráľovstvo tanca II.", info: "Tance, tanečníci, malé a veľké choreogafie."},
    {date:"10.4.2011", city: "Košice", place: "Štátne divadlo", name:"Nie je tanec ako tanec", info: ""},
    {date:"3.12.2011", city: "Košice", place: "Športová hala, Moyzesova", name:"Maratón tanca", info: "Pokus o zápis do Guinessovej knihy rekordov"},
    {date:"31.3.2012", city: "Košice", place: "Štátne divadlo", name:"“Dvojprogram „Hodina deväťdesiatnikom” a „Od Vlada k Vladovi”", info: ""},
    {date:"7.4.2013", city: "Košice", place: "Štátne divadlo", name:"Tanec - Legenda - Rituál", info: ""},
    {date:"16.11.2014", city: "Košice", place: "Štátne divadlo", name:"Co še červeňeje", info: ""},
    {date:"12.12.2015", city: "Košice", place: "Štátne divadlo", name:"Reči o Gemeri", info: ""},
    {date:"3.12.2016", city: "Košice", place: "Štátne divadlo", name:"Jubileum - život s tancom", info: "Program k životnému jubileu choreografa a umeleckého vedúceho Vlada Urbana"},
    {date:"11.12.2016", city: "Košice", place: "Štátne divadlo", name:"Choreografický večer", info: "Jubilant Vlado Urban uvádza svoje choreografie v interpretácii súboru Železiar, Žezlo, Želiezko, Omladina"},
    {date:"7.5.2017", city: "Košice", place: "Štátne divadlo", name:"Zábavky a hry tanečné", info: ""},
    {date:"28.4.2018", city: "Košice", place: "Divadlo Grand", name:"Rusnacka maňira II", info: ""},
    {date:"24.2.2019", city: "Košice", place: "Štátne divadlo", name:"Ňe jeden, ňe dva, aňi ňe tri", info: "Premiéra k 55. výročiu súboru Železiar"},
    {date:"22.3.2020", city: "Košice", place: "Štátne divadlo", name:"Parády a parádičky", info: "Pre coronaopatrenia preložené na 3/2021 "},
    {date:"27.3.2022", city: "Košice", place: "Štátne divadlo", name:"Taka tota naša nouta", info: ""},
    {date:"14.5.2023", city: "Košice", place: "Národné divadlo", name:"Zábavky a hry tanečné II.", info: ""},
    {date:"3.5.2024", city: "Košice", place: "Divadlo Grand", name:"Na ostatňi raz", info: "hudobno-spevácky program pri príležitosti 60. výročia súboru a rozlúčky Andrey Rendošovej so súborom"},
    {date:"4.5.2024", city: "Košice", place: "Národné divadlo", name:"Ňit takoho prekrasnoho", info: "60. výročie súboru"},
    {date:"7.6.2025", city: "Košice", place: "Divadlo Grand", name:"V Tieni", info: "Celovečerný program venovaný Maďarskej, Goralskej, Rómskej a Rusínskej menšine Slovenska."},
]